// <auto-generated />
using System;
using AmirPetProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AmirPetProject.Migrations
{
    [DbContext(typeof(DB))]
    [Migration("20230522195852_update4")]
    partial class update4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AmirPetProject.Models.DataBase.Animals", b =>
                {
                    b.Property<int>("AnimalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalID"));

                    b.Property<int?>("Age")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("CatagoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("CategoryCatagoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnimalID");

                    b.HasIndex("CategoryCatagoryID");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalID = 1,
                            Age = 5,
                            CatagoryID = 2,
                            Description = "Friendly and playful",
                            Name = "Dog",
                            PictureName = "Dog.png"
                        },
                        new
                        {
                            AnimalID = 2,
                            Age = 3,
                            CatagoryID = 2,
                            Description = "Independent and curious",
                            Name = "Cat",
                            PictureName = "Cat.png"
                        },
                        new
                        {
                            AnimalID = 3,
                            Age = 2,
                            CatagoryID = 1,
                            Description = "Energetic and low maintenance",
                            Name = "Lizard",
                            PictureName = "Lizard.png"
                        });
                });

            modelBuilder.Entity("AmirPetProject.Models.DataBase.Catagories", b =>
                {
                    b.Property<int>("CatagoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CatagoryID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CatagoryID");

                    b.ToTable("Catagories");

                    b.HasData(
                        new
                        {
                            CatagoryID = 1,
                            Name = "Reptiles"
                        },
                        new
                        {
                            CatagoryID = 2,
                            Name = "Mammals"
                        },
                        new
                        {
                            CatagoryID = 3,
                            Name = "Aquatic"
                        });
                });

            modelBuilder.Entity("AmirPetProject.Models.DataBase.Comments", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentID"));

                    b.Property<int>("AnimalID")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommentID");

                    b.HasIndex("AnimalID");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentID = 1,
                            AnimalID = 1,
                            Comment = "This dog is adorable!"
                        },
                        new
                        {
                            CommentID = 2,
                            AnimalID = 1,
                            Comment = "I love dogs so much!"
                        },
                        new
                        {
                            CommentID = 3,
                            AnimalID = 2,
                            Comment = "Cats are so cute and cuddly."
                        },
                        new
                        {
                            CommentID = 4,
                            AnimalID = 3,
                            Comment = "I've always wanted a pet lizard!"
                        },
                        new
                        {
                            CommentID = 5,
                            AnimalID = 1,
                            Comment = "Such a friendly and playful dog!"
                        },
                        new
                        {
                            CommentID = 6,
                            AnimalID = 2,
                            Comment = "I have two cats and they bring me so much joy."
                        },
                        new
                        {
                            CommentID = 7,
                            AnimalID = 3,
                            Comment = "Lizards are fascinating creatures."
                        },
                        new
                        {
                            CommentID = 8,
                            AnimalID = 2,
                            Comment = "Cats are great companions."
                        },
                        new
                        {
                            CommentID = 9,
                            AnimalID = 3,
                            Comment = "I'm considering getting a pet lizard now."
                        },
                        new
                        {
                            CommentID = 10,
                            AnimalID = 1,
                            Comment = "I can't resist those puppy eyes!"
                        },
                        new
                        {
                            CommentID = 11,
                            AnimalID = 2,
                            Comment = "Cats make my house feel like a home."
                        },
                        new
                        {
                            CommentID = 12,
                            AnimalID = 3,
                            Comment = "Lizards have such unique personalities."
                        },
                        new
                        {
                            CommentID = 13,
                            AnimalID = 1,
                            Comment = "Dogs are truly man's best friend."
                        },
                        new
                        {
                            CommentID = 14,
                            AnimalID = 2,
                            Comment = "I enjoy watching my cats play and explore."
                        },
                        new
                        {
                            CommentID = 15,
                            AnimalID = 3,
                            Comment = "Having a pet lizard would be so cool."
                        },
                        new
                        {
                            CommentID = 16,
                            AnimalID = 1,
                            Comment = "This dog brings so much happiness into my life."
                        },
                        new
                        {
                            CommentID = 17,
                            AnimalID = 2,
                            Comment = "Cats have such unique personalities."
                        },
                        new
                        {
                            CommentID = 18,
                            AnimalID = 3,
                            Comment = "I find reptiles fascinating."
                        },
                        new
                        {
                            CommentID = 19,
                            AnimalID = 2,
                            Comment = "Cats are independent yet affectionate."
                        },
                        new
                        {
                            CommentID = 20,
                            AnimalID = 3,
                            Comment = "I'm considering getting a pet lizard soon."
                        });
                });

            modelBuilder.Entity("AmirPetProject.Models.DataBase.Animals", b =>
                {
                    b.HasOne("AmirPetProject.Models.DataBase.Catagories", "Category")
                        .WithMany("animals")
                        .HasForeignKey("CategoryCatagoryID");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AmirPetProject.Models.DataBase.Comments", b =>
                {
                    b.HasOne("AmirPetProject.Models.DataBase.Animals", "Animal")
                        .WithMany("Comments")
                        .HasForeignKey("AnimalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("AmirPetProject.Models.DataBase.Animals", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("AmirPetProject.Models.DataBase.Catagories", b =>
                {
                    b.Navigation("animals");
                });
#pragma warning restore 612, 618
        }
    }
}
