// <auto-generated />
using System;
using AmirPetProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AmirPetProject.Migrations
{
    [DbContext(typeof(DB))]
    [Migration("20230524141305_AddedComments")]
    partial class AddedComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AmirPetProject.Models.DataBase.Animals", b =>
                {
                    b.Property<int>("AnimalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalID"));

                    b.Property<int?>("Age")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("CatagoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("CategoryCatagoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnimalID");

                    b.HasIndex("CategoryCatagoryID");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalID = 1,
                            Age = 5,
                            CatagoryID = 2,
                            Description = "Friendly and playful",
                            Name = "Dog",
                            PictureName = "Dog.png"
                        },
                        new
                        {
                            AnimalID = 2,
                            Age = 3,
                            CatagoryID = 2,
                            Description = "Independent and curious",
                            Name = "Cat",
                            PictureName = "Cat.png"
                        },
                        new
                        {
                            AnimalID = 3,
                            Age = 2,
                            CatagoryID = 1,
                            Description = "Energetic and low maintenance",
                            Name = "Lizard",
                            PictureName = "Lizard.png"
                        },
                        new
                        {
                            AnimalID = 4,
                            Age = 10,
                            CatagoryID = 2,
                            Description = "Gentle and intelligent",
                            Name = "Elephant",
                            PictureName = "Elephant.png"
                        },
                        new
                        {
                            AnimalID = 5,
                            Age = 6,
                            CatagoryID = 2,
                            Description = "Powerful and majestic",
                            Name = "Tiger",
                            PictureName = "Tiger.png"
                        },
                        new
                        {
                            AnimalID = 6,
                            Age = 4,
                            CatagoryID = 1,
                            Description = "Sleek and stealthy",
                            Name = "Snake",
                            PictureName = "Snake.png"
                        },
                        new
                        {
                            AnimalID = 7,
                            Age = 8,
                            CatagoryID = 3,
                            Description = "Playful and sociable",
                            Name = "Dolphin",
                            PictureName = "Dolphin.png"
                        },
                        new
                        {
                            AnimalID = 8,
                            Age = 7,
                            CatagoryID = 2,
                            Description = "Tall and graceful",
                            Name = "Giraffe",
                            PictureName = "Giraffe.png"
                        },
                        new
                        {
                            AnimalID = 9,
                            Age = 3,
                            CatagoryID = 3,
                            Description = "Adorable and waddling",
                            Name = "Penguin",
                            PictureName = "Penguin.png"
                        },
                        new
                        {
                            AnimalID = 10,
                            Age = 4,
                            CatagoryID = 2,
                            Description = "Hopping and unique",
                            Name = "Kangaroo",
                            PictureName = "Kangaroo.png"
                        });
                });

            modelBuilder.Entity("AmirPetProject.Models.DataBase.Catagories", b =>
                {
                    b.Property<int>("CatagoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CatagoryID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CatagoryID");

                    b.ToTable("Catagories");

                    b.HasData(
                        new
                        {
                            CatagoryID = 1,
                            Name = "Reptiles"
                        },
                        new
                        {
                            CatagoryID = 2,
                            Name = "Mammals"
                        },
                        new
                        {
                            CatagoryID = 3,
                            Name = "Aquatic"
                        });
                });

            modelBuilder.Entity("AmirPetProject.Models.DataBase.Comments", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentID"));

                    b.Property<int>("AnimalID")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommentID");

                    b.HasIndex("AnimalID");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentID = 1,
                            AnimalID = 5,
                            Comment = "This tiger is absolutely stunning!"
                        },
                        new
                        {
                            CommentID = 2,
                            AnimalID = 3,
                            Comment = "The lizard's colors are so vibrant."
                        },
                        new
                        {
                            CommentID = 3,
                            AnimalID = 10,
                            Comment = "The kangaroo's hopping is fascinating to watch."
                        },
                        new
                        {
                            CommentID = 4,
                            AnimalID = 1,
                            Comment = "This dog is so friendly and playful!"
                        },
                        new
                        {
                            CommentID = 5,
                            AnimalID = 9,
                            Comment = "The penguin looks adorable with its waddling."
                        },
                        new
                        {
                            CommentID = 6,
                            AnimalID = 4,
                            Comment = "Elephants are such gentle giants."
                        },
                        new
                        {
                            CommentID = 7,
                            AnimalID = 8,
                            Comment = "The giraffe's long neck is impressive."
                        },
                        new
                        {
                            CommentID = 8,
                            AnimalID = 2,
                            Comment = "The cat's independence is intriguing."
                        },
                        new
                        {
                            CommentID = 9,
                            AnimalID = 7,
                            Comment = "Dolphins are known for their playful nature."
                        },
                        new
                        {
                            CommentID = 10,
                            AnimalID = 3,
                            Comment = "I love how energetic and low maintenance lizards are."
                        },
                        new
                        {
                            CommentID = 11,
                            AnimalID = 7,
                            Comment = "The dolphin's agility in the water is remarkable."
                        },
                        new
                        {
                            CommentID = 12,
                            AnimalID = 5,
                            Comment = "The tiger's roar sends chills down my spine."
                        },
                        new
                        {
                            CommentID = 13,
                            AnimalID = 10,
                            Comment = "Kangaroos have a unique way of moving."
                        },
                        new
                        {
                            CommentID = 14,
                            AnimalID = 6,
                            Comment = "Snakes are fascinating creatures with their sleek bodies."
                        },
                        new
                        {
                            CommentID = 15,
                            AnimalID = 8,
                            Comment = "Giraffes are such graceful animals."
                        },
                        new
                        {
                            CommentID = 16,
                            AnimalID = 1,
                            Comment = "I can't resist the cuteness of this dog!"
                        },
                        new
                        {
                            CommentID = 17,
                            AnimalID = 4,
                            Comment = "The elephant's intelligence is remarkable."
                        },
                        new
                        {
                            CommentID = 18,
                            AnimalID = 9,
                            Comment = "Penguins are perfectly adapted to their icy habitats."
                        },
                        new
                        {
                            CommentID = 19,
                            AnimalID = 2,
                            Comment = "Cats have such curious and mischievous personalities."
                        },
                        new
                        {
                            CommentID = 20,
                            AnimalID = 6,
                            Comment = "The snake's stealthy movements are captivating."
                        });
                });

            modelBuilder.Entity("AmirPetProject.Models.DataBase.Animals", b =>
                {
                    b.HasOne("AmirPetProject.Models.DataBase.Catagories", "Category")
                        .WithMany("animals")
                        .HasForeignKey("CategoryCatagoryID");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AmirPetProject.Models.DataBase.Comments", b =>
                {
                    b.HasOne("AmirPetProject.Models.DataBase.Animals", "Animal")
                        .WithMany("Comments")
                        .HasForeignKey("AnimalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("AmirPetProject.Models.DataBase.Animals", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("AmirPetProject.Models.DataBase.Catagories", b =>
                {
                    b.Navigation("animals");
                });
#pragma warning restore 612, 618
        }
    }
}
