name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        path: src

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore src/AmitPetProject.csproj

    - name: Build
      run: dotnet build src/AmitPetProject.csproj --no-restore

    - name: Test
      run: dotnet test src/AmitPetProject.Tests/AmitPetProject.Tests.csproj --no-build --verbosity normal
